#!/bin/sh

set -e

case "$1" in

  purge)
    systemctl stop vault-rest.service
    systemctl disable vault-rest.service

    systemctl stop vault.service
    systemctl disable vault.service

    (rm /lib/systemd/system/vault-rest.service || :)
    (rm /lib/systemd/system/vault-unit.service || :)

    (rm /etc/init/vault.conf || :)

    systemctl daemon-reload
    systemctl reset-failed
  ;;

  remove)
    systemctl mask vault.service
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
