#!/bin/sh

set -e

enable() {
  wanted_by=$(cat /lib/systemd/system/${1} | sed -n -e 's/^.*WantedBy=//p')
  mkdir -p /etc/systemd/system/${wanted_by}.wants
  ln -s \
    "/lib/systemd/system/${1}" \
    "/etc/systemd/system/${wanted_by}.wants/${1}"
}

case "$1" in

  configure)
    if [ -f /etc/init/vault.conf ] ; then
      enable vault.path
      enable vault.service
      enable vault-rest.service
      (systemctl daemon-reload >/dev/null 2>&1 || :)
      (systemctl start vault.service >/dev/null 2>&1 || :)
      (systemctl start vault-rest.service >/dev/null 2>&1 || :)
      (systemctl start vault.path >/dev/null 2>&1 || :)
    else
      (>&2 echo "/etc/init/vault.conf file not found")
      exit 1
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    (>&2 echo "postinst called with unknown argument \ `$1`")
    exit 1
  ;;

esac

exit 0
