#!/bin/sh

set -e

delete() {
  if [ -f "${1}" ] ; then
    rm "${1}"
  fi
}

delete_service_files() {
  delete /etc/systemd/vault.service.wants/vault-rest.service
  delete /lib/systemd/system/vault-rest.service

  delete /etc/systemd/vault.service.wants/vault-unit@.service
  delete /lib/systemd/system/vault-unit@.service

  delete /etc/systemd/vault.service.wants/vault.path
  delete /lib/systemd/system/vault.path

  delete /etc/systemd/multi-user.target.wants/vault.service
  delete /lib/systemd/system/vault.service
}

delete_displace_files() {
  delete /etc/init/vault.conf
}

case "$1" in

  purge)
    delete_service_files
    delete_displace_files
    (systemctl daemon-reload >/dev/null 2>&1 || :)
    (systemctl reset-failed >/dev/null 2>&1 || :)
  ;;

  remove)
    (systemctl -a -t service --no-legend  | awk '$1 ~ /vault/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    delete_displace_files
    (systemctl daemon-reload >/dev/null 2>&1 || :)
  ;;

  upgrade|deconfigure)
    (systemctl stop vault >/dev/null 2>&1 || :)
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
