#!/bin/sh

set -e

case "$1" in

  install|upgrade)
    if [ ! -f "/etc/init/vault.conf" ] ; then
      mkdir -p /etc/init
      touch /etc/init/vault.conf

      echo "VAULT_STORAGE=/data" > /etc/init/vault.conf
      echo "VAULT_LOG_LEVEL=INFO" >> /etc/init/vault.conf
      echo "VAULT_JOURNAL_SATURATION=200" >> /etc/init/vault.conf
      echo "VAULT_SNAPSHOT_SCANINTERVAL=120s" >> /etc/init/vault.conf
      echo "VAULT_METRICS_REFRESHRATE=1s" >> /etc/init/vault.conf
      echo "VAULT_METRICS_OUTPUT=/opt/vault/metrics/metrics.json" >> /etc/init/vault.conf
      echo "VAULT_LAKE_HOSTNAME=localhost" >> /etc/init/vault.conf
    fi
  ;;

  abort-upgrade)
  ;;

  *)
    (>&2 echo "preinst called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
