.nh
.TH "VAULT-UNIT" "1" "Jul 2020" "Vault Unit" "OpenBank Account Vault Manual"
.sp
.SH "NAME"
lake \- starts openbank account vault account unit
.SH "SYNOPSIS"
.sp
.nf
\fIvault-unit
.fi
.sp
.SH "DESCRIPTION"
.sp
The vault unit stores account journal and negotiates account balance blocation.
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
