.nh
.TH "VAULT-REST" "1" "Jul 2020" "Vault Unit" "OpenBank Account REST Server Manual"
.sp
.SH "NAME"
lake \- starts openbank account vault REST server
.SH "SYNOPSIS"
.sp
.nf
\fIlake
.fi
.sp
.SH "DESCRIPTION"
.sp
The vault rest provides REST server for accessing and manipulating vault units.
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
